source "https://rubygems.org"
gem "oscar"
gem "vagrant-hosts"
gem "vagrant-pe_build"
gem "vagrant-auto_network"
gem "vagrant-vbox-snapshot"
# gem "vagrant", :github => "mitchellh/vagrant", :tag => "v1.7.4"
gem "vagrant-config_builder"